# Generated by Django 6.0.2 on 2026-02-15 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('item_type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=5)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('books', 'Books'), ('clothing', 'Clothing'), ('accessories', 'Accessories'), ('id_cards', 'ID Cards'), ('keys', 'Keys'), ('bags', 'Bags'), ('other', 'Other')], default='other', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('date_item', models.DateField(help_text='Date when item was lost or found')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('resolved', 'Resolved')], default='open', max_length=10)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_reported'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Describe why you think this is yours')),
                ('date_claimed', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('claimed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='items.item')),
            ],
            options={
                'ordering': ['-date_claimed'],
            },
        ),
    ]
